language: python
os: linux
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - python ustvnow.py -u $USTVNOW_USERNAME -p $USTVNOW_PASSWORD -c wgal -q $USTVNOW_QUALITY -d
  - python -m pycodestyle ustvnow.py
